### ISSUE TITLE
Mysql Maven project doesn't work out of the box with TestResources

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-starter#1522]
If you create a maven app with the mysql feature, the mysql driver doesn't end up on the classpath of the test-resources

```
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.testcontainers.containers.JdbcDatabaseContainer.getJdbcDriverInstance(JdbcDatabaseContainer.java:200)
        ... 83 common frames omitted
```

The workaround is to change the maven plugin config from

```
          <configuration>
            <classpathInference>false</classpathInference>
```

To

```
          <configuration>
            <classpathInference>true</classpathInference>
```

@alvarosanchez should we be setting this to `true` by default for everything using test-resources?

Micronaut 3.7.3

**Comment by alvarosanchez** [comment]
This is "a duplicate" of https://github.com/micronaut-projects/micronaut-test-resources/issues/79

The initial intention had been that starter should add not only the test-resources module dependency, but also the driver:

https://micronaut-projects.github.io/micronaut-maven-plugin/latest/examples/test-resources.html#adding_modules_or_libraries_to_the_test_resources_service_classpath

So in this regard, starter is "broken".

The fact that classpath inference works is a big surprise, though. @melix is this a recent change in Test Resources?

**Comment by melix** [comment]
Classpath inference is enabled by default in the Gradle plugin and has always worked, AFAIK: if a driver is explicitly on classpath, it is automatically added to the test resources service classpath. The pb in the issue you linked is a bit different: if production code doesn't need a MySQL driver, then there's no mysql dependency (e.g in `implementation` or `<scope>runtime</scope>`, and therefore we _don't_ infer that a MySQL driver should be added to the test resources classpath. This is the case if you use a reactive driver like `dev.miku:r2dbc-mysql`: this driver is enough for production, but for tests, Testcontainer wants a JDBC driver. We don't infer one by default, because it would require us to build a "database" of possible drivers and detect conflicts.
