### ISSUE TITLE
Junit vs JUnit

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-starter#825]
Currently, the test framework options shown in the UI are `Junit`, `Spock`, and `Kotest`.

I think `JUnit` is correct, vs `Junit`.

**Comment by eahrold** [comment]
This is strange, not sure what's going on because it should have been fixed by https://github.com/micronaut-projects/micronaut-starter/pull/633, but the api is still returning the title case value. I'll look into what's going on with the message source.

```
// [GET] https://launch.micronaut.io/select-options
{
...
    "test": {
        "options": [
            {
                "description": "Junit",
                "name": "junit",
                "value": "JUNIT",
                "label": "Junit",
                "_links": {}
            },
}
```

**Comment by jeffscottbrown** [comment]
The UI still shows **Junit**.

**Comment by JasonTypesCodes** [comment]
I've transferred this to starter as the service is returning "Junit"

**Comment by eahrold** [comment]
It’s definitely an issue with the deployed build because there is a test for it and locally it’s returns the correct value. 

It uses a resource bundle MessageSource

https://github.com/micronaut-projects/micronaut-starter/blob/1f6f3366550e5db5b0b0eaeeb56d73549ecac3d5/starter-api/src/main/java/io/micronaut/starter/api/options/SelectOptionsController.java#L53

I’m not sure how to tell the prod build to include that file. Any guidance there would be helpful.

**Comment by ilopmar** [comment]
@eahrold thanks for tracking down the problem. I've submitted #827 that includes the properties file in the native-image. It should fix the problem.
