### ISSUE TITLE
Unable to resolve oraclecloud-atp

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter#947]
`oracle-cloud-atp` features adds the dependency `io.micronaut.oraclecloud:micronaut-oraclecloud-atp` which cannot be resolved. 

```
A problem occurred configuring root project 'micronautguide'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find io.micronaut.oraclecloud:micronaut-oraclecloud-atp:.
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html


```

**Comment by pgressa** [comment]
The cause is that this commit https://github.com/micronaut-projects/micronaut-oracle-cloud/commit/a11982ec2dd7261ce6484587c2a2dab3e8959f87#diff-0d634959c8276ae976e39ba475e63d0b9ec27824470c79f1971f58fe37c46325L64 has changed the default java version from 11 to 8, as it is specifed in the template. Unfortunately the ATP module is  11+ module only, so in case of running on java8 the module is not resolved and thus not released. I have fixed the module and release 2.0.2.

We have discussed possible solution with @ilopmar so maybe he will come with implemented solution when the default java env would be resolved from repo/organisation variables, allowing us to configure java11 for oraclecloud without touching the workflow files.

**Comment by ilopmar** [comment]
I didn't know I volunteered to implement it :rofl:

**Comment by sdelamo** [comment]
@pgressa 

> have fixed the module and release 2.0.2.

Have you updated the BOM ?

**Comment by pgressa** [comment]
@ilopmar since I don't have permission to configure the organisation variables, I can't do that 
@sdelamo if you mean micronaut-core bom, it should be updated https://github.com/micronaut-projects/micronaut-core/pull/6377

**Comment by ilopmar** [comment]
@pgressa I was kidding, I'll add it to my TODO list :smiley:

**Comment by sdelamo** [comment]
> @sdelamo if you mean micronaut-core bom, it should be updated [micronaut-projects/micronaut-core#6377](https://github.com/micronaut-projects/micronaut-core/pull/6377)

that was merged after 3.1.1 was released right?

**Comment by pgressa** [comment]
@sdelamo yes

**Comment by jameskleeh** [comment]
So is this issue resolved then?
